[credentials]
client_email = "firebase-adminsdk-9c1d2@methiong.iam.gserviceaccount.com"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCySFQIFr5OkFOw\n...\n-----END PRIVATE KEY-----\n"
